### PR TITLE
new routers: DomainRouter and ModuleRouter

### PR DESCRIPTION
**Pull request by JanTvrdik**
Refactoring based on https://github.com/nextras/static-router/issues/2

Obviously, I will write tests and possibly handle the BC break better if the idea is accepted.

### CODE REVIEW

**Comment by JanTvrdik** [comment]
Any thoughts, @dg? It's been a month.

**Comment by dg** [comment]
I haven't thought about it yet.

**Comment by foxycode** [comment]
I like both new routers. I actually using routes for more subdomains and it is annoying write `something.%domain%` everywhere. :+1:

**Comment by EdaCZ** [comment]
Why is this closed, please?

This PR seems like a good idea to me.

**Comment by dg** [comment]
Github fools you ;)

**Comment by EdaCZ** [comment]
Oh. Now I see... Great :-)

**Comment by JanTvrdik** [comment]
ping @dg What's the status?

**Comment by fprochazka** [comment]
This is not sufficient. Your router is way too strict. I'm preparing a modified version of your router that works better. Just needs s bit of polishing.

**Comment by fprochazka** [comment]
I've ended up using this version on production. https://gist.github.com/fprochazka/769596173ee4e1fc02b2

- the first argument is expression that will be used if the domain of http request doesn't match the other arguments, so the router is still able to generate url
- the second argument is used for allowing the current httprequest domain to be used for constructing urls. For example you have `testing.` subdomain or `beta.` and the app should be able to work with that without redirecting to `www.`
- the third argument is for matching domains

**Comment by f3l1x** [comment]
:+1: for DomainRouter and ModuleRouter

**Comment by JanTvrdik** [comment]
self note: collision between URL and presenter tree.

**Comment by mabar** [comment]
Is there any chance it will be merged in 3.0? I was creating something similar recently and I absolutely like this idea.

**Comment by f3l1x** [comment]
I like an idea too. I think I gonna create some classes in [contributte/application](https://github.com/contributte/application).

**Comment by dg** [comment]
I want to add to RouteList syntactic sugar similar to forms, ie. instead of

```php
$router = new RouteList();
$router[] = new Route(...);
$router[] = new Route(...);
$router[] = new MyRouter(...);
```

to allow something like

```php
$router = new RouteList();
$router->addRoute(...);
$router->addRoute(...);
$router->add(new MyRouter...);
```

Because there is no need to deal with class names so much. And classes can be confusing after merging #208.

In relation to this PR original code:

```php
$router = new RouteList();
$router[] = new DomainRouter('blog.example.com', new RouteList([
    new ModuleRouter('Admin', new RouteList([
        new Route('...'),
        new Route('...'),
    ])),
    new ModuleRouter('Front', new RouteList([
        new Route('...'),
        new Route('...'),
    ])),
]));

$router[] = new DomainRouter(
    'simple.example.com',
    new SimpleRouter(),
);
```

can be written this way:

```php
$router = new RouteList();
$router->withDomain('blog.example.com')
	withModule('Admin')
		->addRoute('...')
		->addRoute('...')
	end() // or store $blogRouter = $router->withDomain('blog.example.com'); and continue with $blogRouter->withModule(...)
	withModule('Front')
		->addRoute('...')
		->addRoute('...');

$router->withDomain('simple.example.com')
	->add(new SimpleRouter());
```

What do you think?

**Comment by f3l1x** [comment]
I like it! 👍

**Comment by dg** [comment]
Closed by #208

**Pull request closed without merging**
