### PR TITLE
VaribaleTemplate: add getParameters() method to improve back compatability

### PR DESCRIPTION
**Pull request by xificurk**
Quite a few custom macros use something like: https://github.com/brabijan/images/blob/master/src/Brabijan/Images/Macros/Latte.php#L138

### CODE REVIEW

**Comment by xificurk** [comment]
Hm, travis failed, but as far as I can tell, it's unrelated with this change.

**Comment by dg** [comment]
Hmmm, there is not getParameters()? It extends Latte\Template.

**Comment by xificurk** [comment]
There is, but it's returning parameters of `VariableTemplate` (which is empty array). You need to return parameters of the underlying latte template object.

**Comment by dg** [comment]
Oh! Please can you fix typo in commit message: `VariableTemplate`

**Comment by xificurk** [comment]
Good catch! Fixed.

**Comment by dg** [comment]
Thanks

**Pull request merged**
