### PR TITLE
Route: fix old Nette\Callback name

### PR DESCRIPTION
**Pull request by TomasVotruba**
New namespace is `Nette\Utils\Callback`.

### CODE REVIEW

**Comment by dg** [comment]
This is for compatibility with old name.

**Comment by TomasVotruba** [comment]
I see. What about using to both to make this clear in the code as well?

**Comment by dg** [comment]
Nette\Utils\Callback is static class.

**Comment by TomasVotruba** [comment]
I don't understand.

**Comment by dg** [comment]
Me too ;)

**Comment by enumag** [comment]
@TomasVotruba An instance of Nette\Utils\Callback is NOT callable.

**Comment by TomasVotruba** [comment]
@enumag I see. They're different.

That's settled then.

**Pull request closed without merging**
