### PR TITLE
Remove typehint for $message in flashMessage

### PR DESCRIPTION
**Pull request by venca-x**
I'm removing typehint for display Nette\Utils\Html in $message

- bug fix? no
- new feature? no
- BC break? no

### CODE REVIEW

**Comment by CZechBoY** [comment]
You should add additional check for type Html|string and throw exception if it is not.

**Comment by dg** [comment]
Thx

**Comment by JanTvrdik** [comment]
It would be nice to add a test specifically for `Nette\Utils\Html` to make sure it continues to work in the future.

Adding a typehint for `Nette\Utils\Html|string` is also a possibility but depends on whether the intention is to allow only `Nette\Utils\Html` instances or any instances with `__toString` method is fine. What do you think @dg?

**Comment by dg** [comment]
I would leave it completely free. It is like template parameter.

**Comment by CZechBoY** [comment]
@milo so you are using more parameters than this definition and you have your own template implementation, right?

**Comment by milo** [comment]
I was planning to write template macro but I stuck with linked trait due to lack of time.

**Pull request merged**
