### PR TITLE
Snippets: do not render snippets from template which is included using includeblock macro

### PR DESCRIPTION
**Pull request by matej21**
- fixes nette/nette#1510

### CODE REVIEW

**Comment by matej21** [comment]
ping @dg

**Comment by dg** [comment]
Is it BC break?

**Comment by dg** [comment]
@matej21 please can you rebase it, I'll merge it

**Comment by matej21** [comment]
rebased (it is failing because the test depends on nette/latte#34)

> Is it BC break?

I hope it is not :)

**Comment by dg** [comment]
Thanks

**Pull request merged**
