### PR TITLE
some classes & members marked as final (BC break)

### PR DESCRIPTION
**Pull request by dg**
This among others reverts commit 45ed648caeb7dd94c6f38bd50d7526606a7bcc14

- BC break? yes

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This might lead to some magic remove. Great job :+1: 

Could :-1:s add some comments with reasoning please?

**Comment by TomasVotruba** [comment]
Well, we can:

* https://phpfashion.com/how-to-mock-final-classes
* https://www.tomasvotruba.cz/blog/2019/03/28/how-to-mock-final-classes-in-phpunit/

**Comment by lukasojd** [comment]
-1 again

https://github.com/nette/security/commit/c7cc80bbe5f8db6346b7008f88eb3b478380d6cd

**Comment by lukasojd** [comment]
> @lukasojd Well, we can:
> 
>     * https://phpfashion.com/how-to-mock-final-classes
> 
>     * https://www.tomasvotruba.cz/blog/2019/03/28/how-to-mock-final-classes-in-phpunit/

Thank you. Final is evel and I will not use dg/bypass-finals. Author commits is author package. DG need more money and he insert keyword final everywhere.

**Comment by mabar** [comment]
> DG need more money and he insert keyword final everywhere.

That's very dumb claim, you know? Please stop being an asshole complaining everywhere about few final getters because you somehow didn't get how to solve problem even after I explained it to you several times. How could you complain about bypassing finals and be okay with mocks same time? Both is bad magic to solve edge cases and this is really not the case in which you really need to use it.

**Comment by janfejtek** [comment]
My use case is that I have custom Authenticator, User and Identity classes. 
Originally I override getUser in presenter and it was returning CustomUser class (basically just hinting PhpStorm). But now, PhpStorm is showing errors about missing methods. Because I had to remove getUser from my presenter as well as getIdentity from CustomUser
PHP 7.4 supports covariance so more specific return type should not be a problem in overridden method

Or am I doing it wrong?

**Pull request merged**
