### PR TITLE
Removed TABs from routing panel

### PR DESCRIPTION
**Pull request by meridius**
- bug fix? **yes**
- new feature? **no**
- BC break? **no**

Because of indentation within the `<code>` tags the Tracy routing panel is rendering TAB characters in data of *Defaults* and *Matched as* columns. Thus making its content full of white space, lengthy and hard to read due to needed scrolling. 

This PR fixes the described issue by rewriting rendering of the problematic `<code>` tags.  
The second commit just removes unnecessary (in my opinion) PHP tags, making given section easier to read.

An finally, even if this PR adds a few code lines, I believe it is for better readability and the rest of the file should be rewritten in the same fashion someday.

### CODE REVIEW

**Comment by dg** [comment]
How I can reproduce the problem?

**Comment by meridius** [comment]
You don't see it? That's weird. It is happening on a clean `composer create-project nette/web-project` for me.

**Comment by dg** [comment]
Can you send screenshot?

**Comment by meridius** [comment]
http://imgur.com/a/UuYtt

**Comment by meridius** [comment]
And with text selected http://imgur.com/a/wRcCX

**Comment by dg** [comment]
Try update Tracy

**Comment by meridius** [comment]
Heh, fun. 
Fixed, thanks 😄

**Pull request closed without merging**
