### PR TITLE
SimpleRouter: add support for $defaultFlags

### PR DESCRIPTION
**Pull request by voda**
My use case is as described here: https://forum.nette.org/cs/3184-https-mi-automaticky-presmeruje-na-http#p93043

Its a private project, so SimpleRouter is good enough and it is running https on server and http on local machine.

### CODE REVIEW

**Comment by JanTvrdik** [comment]
Why not just pass `$flags` argument to constructor? Do you have multiple instances of `SimpleRouter`?

**Comment by dg** [comment]
Static variables are bad…

**Comment by voda** [comment]
I have router defined as a service in config.neon, so cant use a parameter because parameter needs to be set before container is created, but to detect http/https I need HttpRequest from container.

So best variant is custom factory?

**Comment by enumag** [comment]
Actually you can set constructor parameters in config.neon.

https://doc.nette.org/en/2.3/configuring#toc-custom-services

**Comment by voda** [comment]
I know that, but how to write `$container->getService('httpRequest')->isSecured() ? Route::SECURED : 0` in neon?

**Comment by enumag** [comment]
In my opinion this flag should not be based on the current request. Why do you do that?

**Comment by voda** [comment]
Because i use https on server and http on localhost. Redirect from http to https is handled by webserver.

**Comment by enumag** [comment]
I solve that differently - parameter in config.neon that defaults to `Route::SECURED` but I override it to 0 in my local.neon on localhost. No need to complicate the application.

**Comment by milo** [comment]
@voda 
```php
class DefaultRouterFlags
{
    public static function get()
    {
        return ....;
    }
}
```

```
services:
    - SimpleRouter(flags: DefaultRouterFlags::get())
```

**Comment by voda** [comment]
Ok, thanks for the suggestions.

**Pull request closed without merging**
