### PR TITLE
added LinkGenerator

### PR DESCRIPTION
**Pull request by dg**
Similar to https://github.com/nextras/link-factory. It should be part of framework. Solves an issue with generating links in emails.

### CODE REVIEW

**Comment by JanTvrdik** [comment]
* Another name to consider – `Linker`.
* The code is hard to read for no good reason due to aggressive inlining.
* I don't like the dependency on `Application\UI`. We may even consider putting this to `nette/routing` if you ever choose to [split nette/application](http://forum.nette.org/en/21178-rfc-refactoring-nette-application-dependencies).

**Comment by fprochazka** [comment]
Adding it to routing seems like a good idea.

**Comment by dg** [comment]
"Linker" is something similar to compiler.

**Comment by dg** [comment]
Split nette/application to nette/routing will take some time, so it is not goal for 2.3.

**Comment by JanTvrdik** [comment]
@dg I know but it should be taken into consideration.

**Comment by JanTvrdik** [comment]
Because you decided to write it more generally (support presenters without `action`) parameter, it may be nice to allow any value in `action` parameter, ie.

~~~php
if (!preg_match(...)) {
    throw new UI\InvalidLinkException(...);
} elseif ($m[2]) {
    $params[UI\Presenter::ACTION_KEY] = $m[2]
}
~~~

This would allow programmers to write
~~~php
$generator->link('Foo:', ['action' => $arr]);
~~~

**Comment by dg** [comment]
Good point

**Comment by Caspern** [comment]
Wouldn't be better to generate relative links by default and allow ```//Presenter:default``` syntax for absolute ones?

**Pull request merged**
