### PR TITLE
Extensions: used services and config aliases [WIP]

### PR DESCRIPTION
**Pull request by dg**
See nette/di#29 and nette/bootstrap#32

### CODE REVIEW

**Comment by dg** [comment]
I have absolutely no idea how to define, that a bridge requires nette/di in some version…

**Comment by xificurk** [comment]
I think current requirement of `"nette/di": "~2.3"` is just fine. What's the problem?

**Comment by dg** [comment]
nette/application requires DI, so it is fine. But I have problem with nette/database.

**Comment by xificurk** [comment]
I'm for adding conflict to composer.json, see proposed nette/mail#6

**Comment by dg** [comment]
It is good idea. And why conflict with whole nette/nette 2.2?

**Comment by xificurk** [comment]
It's "<2.2"... I haven't changed that ;)

**Comment by dg** [comment]
Mea culpa ;)

**Pull request merged**
