### PR TITLE
Route: Added domain name (%domainName%) (Needed rebase)

### PR DESCRIPTION
**Pull request by GcoreCZ**
better use for location by tld.

**example:**
`$router[] = new Route('//[!www.]%domainName%.<locale cz|sk>/radce-podekovani','Radce:podekovani');`

### CODE REVIEW

**Comment by dg** [comment]
@GcoreCZ sorry I force repushed the last commit in master, can you rebase it and repush?

**Comment by GcoreCZ** [comment]
@dg ok, no problem, I'll repush.

**Comment by dg** [comment]
Why closed?

**Comment by GcoreCZ** [comment]
so because is new https://github.com/nette/application/pull/129 with test etd.., or Have I reopen it?

**Comment by dg** [comment]
Aha, ok.

**Pull request closed without merging**
