### PR TITLE
Remove nette/reflection

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by JanTvrdik** [comment]
Good job! Another thing I can cross off my todolist.

**Comment by dg** [comment]
I think revert actually fixes this bug, see original commit https://github.com/nette/nette/commit/35bb0ce4beaa9ba9f71e28ff3a09d8c236aafce6

**Comment by dg** [comment]
I changed this PR, PresenterComponentReflection still extends `Nette\Reflection\ClassType` to maintain BC.

**Comment by JanTvrdik** [comment]
@dg `PresenterComponentReflection` is `@internal` class, what exactly would be broken?

**Comment by dg** [comment]
I think that nothing, but just for sure I'll do this change in 2.4-dev.

**Comment by JanTvrdik** [comment]
That seems like a strange reason to keep the dependency. How is the situation here different from nette/di where you have removed the dependency?

**Comment by enumag** [comment]
@JanTvrdik The difference is `PresenterComponent::getReflection()`. Even now `Object::getReflection()` still returns `Nette\Reflection\ClassType` which would break for PresenterComponent.

**Pull request merged**
