### PR TITLE
Class Link is no longer marked as internal.

### PR DESCRIPTION
**Pull request by foxycode**

### CODE REVIEW

**Comment by dg** [comment]
Commit message :-(((

**Comment by foxycode** [comment]
@dg I don't know what else to write, you can tell me and I update it.

**Comment by dg** [comment]
Just try to be consistent with other messages

**Comment by foxycode** [comment]
@dg Hope this is ok.

**Comment by JanTvrdik** [comment]
Much better! To make it perfect it should not end with full stop and instead the word "flag" I would you "annotation".

**Comment by foxycode** [comment]
@JanTvrdik done

**Comment by dg** [comment]
:+1:

**Pull request merged**
